ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS retry_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS retry_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_attempt_at DATETIME(6),
    ADD COLUMN IF NOT EXISTS failure_reason VARCHAR(1024);
